@echo off
title Compiling smart contracts...
echo Compiling smart contracts...
call truffle compile
echo.
start /b call ./start-ganache-cli.bat <NUL >ganache-output.txt
title Running Local Blockchain...
echo Running Local Blockchain...
:REPEAT:
TIMEOUT 1 /NOBREAK >NUL
find "Listening" ganache-output.txt >nul && echo. && call "./start-geth.bat"
goto REPEAT