using Nethereum.Contracts;
using Nethereum.Geth;
using Nethereum.Hex.HexTypes;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Web3;
using Newtonsoft.Json.Linq;
using System;
using System.IO;
using System.Numerics;
using System.Threading;
using System.Threading.Tasks;

namespace ContractUtils {
	/// <summary>
	/// Contains useful functions to deploy and manage Ethereum contracts and function calls using Nethereum
	/// </summary>
	public static class ContractUtil {
		/// <summary>
		/// The Web3 object used to interface with 
		/// </summary>
		public static readonly Web3 Web3 = new Web3(ConfigParams.NodeUrl);
		/// <summary>
		/// The Ethereum node interface
		/// </summary>
		public static readonly Web3Geth Node = new Web3Geth(ConfigParams.NodeUrl);

		/// <summary>
		/// Gets the specified Ganache-Cli wallet address
		/// </summary>
		/// <param name="path">The path of the file containing the Ganache-Cli output</param>
		/// <param name="walletIndex">The wallet index between 0 and 9 (the default is 0)</param>
		/// <param name="timeoutSeconds">The timeout in seconds for the file to be found (default is 120)</param>
		public static string GetWalletAddressFromGanacheLog(string path, int walletIndex = 0, int timeoutSeconds = 120) {
			for (int i = 0; i < timeoutSeconds; i++) {
				string content;
				using (FileStream stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)) {
					using (StreamReader reader = new StreamReader(stream)) {
						content = reader.ReadToEnd();
					}
				}
				string search_string = "(" + walletIndex + ")";
				int index = content.IndexOf(search_string);
				if (index == -1) {
					Thread.Sleep(1000);
				} else {
					index += search_string.Length + 1;
					int end = index;
					while ((end < content.Length) && !(string.IsNullOrWhiteSpace(content.Substring(end, 1)))) {
						end++;
					}
					return content.Substring(index, end - index).Trim();
				}
			}
			throw new Exception("Wallet address could not be loaded, operation timeout exceeded");
		}

		/// <summary>
		/// Unlocks the specified wallet using the given password
		/// </summary>
		/// <param name="wallet">The address of the wallet to unlock</param>
		/// <param name="password">The password of the wallet</param>
		/// <param name="timeoutSeconds">The operation timeout in seconds</param>
		public static Task<bool> UnlockWallet(string wallet, string password, int timeoutSeconds = 120) {
			return Web3.Personal.UnlockAccount.SendRequestAsync(wallet, password, new HexBigInteger(new BigInteger(timeoutSeconds)));
		}

		/// <summary>
		/// Gets the transaction receipt from the specified transaction
		/// </summary>
		/// <param name="transactionHash">The hash of the transaction whose receipt to obtain</param>
		/// <param name="retryCount">The maximum number of retries if an error occurs</param>
		public static async Task<TransactionReceipt> GetReceipt(string transactionHash, int retryCount = 10) {
			TransactionReceipt receipt = null;
			for (int i = 0; i < retryCount && receipt == null; i++) {
				receipt = await Web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(transactionHash);
			}
			return receipt;
		}

		/// <summary>
		/// Deploys the specified contract into the current node specified in the config file
		/// </summary>
		/// <param name="abi">The JSON ABI of the contract</param>
		/// <param name="byteCode">The compiled bytecode of the contract</param>
		/// <param name="wallet">The wallet address of the contract owner</param>
		/// <param name="gas">The gas value</param>
		/// <param name="gasPrice">The gas price</param>
		/// <param name="value">The initial value of the contract</param>
		/// <param name="retryCount">The maximum number of retries if an error occurs</param>
		/// <param name="constructorParams">The values to pass to the contract constructor</param>
		public static async Task<DeployedContract> DeployContract(string abi, string byteCode, string wallet, HexBigInteger gas, HexBigInteger gasPrice, HexBigInteger value, int retryCount = 10, params object[] constructorParams) {
			string transactionHash = await Web3.Eth.DeployContract.SendRequestAsync(abi, byteCode, wallet, gas, gasPrice, value, constructorParams);
			TransactionReceipt receipt = await GetReceipt(transactionHash, retryCount);
			return new DeployedContract(Web3.Eth.GetContract(abi, receipt.ContractAddress), receipt);
		}

		/// <summary>
		/// Deploys the specified contract into the current node specified in the config file
		/// </summary>
		/// <param name="jsonPath">The path to the JSON ABI of the contract that is generated by Truffle</param>
		/// <param name="wallet">The wallet address of the contract owner</param>
		/// <param name="gas">The gas value</param>
		/// <param name="gasPrice">The gas price</param>
		/// <param name="value">The initial value of the contract</param>
		/// <param name="retryCount">The maximum number of retries if an error occurs</param>
		/// <param name="constructorParams">The values to pass to the contract constructor</param>
		public static Task<DeployedContract> DeployContract(string jsonPath, string wallet, HexBigInteger gas, HexBigInteger gasPrice, HexBigInteger value, int retryCount = 10, params object[] constructorParams) {
			JObject json = (JObject) Newtonsoft.Json.JsonConvert.DeserializeObject(File.ReadAllText(jsonPath));
			return DeployContract(json["abi"].ToString(), json["bytecode"].ToString(), gas, gasPrice, value, retryCount, constructorParams);
		}

		/// <summary>
		/// Deploys the specified contract using default values into the current node specified in the config file
		/// </summary>
		/// <param name="jsonPath">The path to the JSON ABI of the contract that is generated by Truffle</param>
		/// <param name="wallet">The wallet address of the contract owner</param>
		/// <param name="constructorParams">The values to pass to the contract constructor</param>
		public static Task<DeployedContract> DeployContract(string jsonPath, string wallet, params object[] constructorParams) {
			return DeployContract(jsonPath, wallet, ConfigParams.DefaultGas, ConfigParams.DefaultGasPrice, ConfigParams.DefaultValue, 10, constructorParams);
		}

		/// <summary>
		/// Calls the specified function as a read operation
		/// </summary>
		/// <typeparam name="T">The return type of the function</typeparam>
		/// <param name="contract">The contract instance on which to invoke the function</param>
		/// <param name="functionName">The name of the function to invoke</param>
		/// <param name="functionParams">The parameters to pass to the function</param>
		public static Task<T> CallRead<T>(this Contract contract, string functionName, params object[] functionParams) {
			return contract.GetFunction(functionName).CallAsync<T>(functionParams);
		}

		/// <summary>
		/// Calls the specified function as a read operation
		/// </summary>
		/// <typeparam name="T">The return type of the function</typeparam>
		/// <param name="function">The isntance of the function to invoke, which is the object returned by contractInstance.GetFunction("functionName")</param>
		/// <param name="functionParams">The parameters to pass to the function</param>
		public static Task<T> CallRead<T>(this Function function, params object[] functionParams) {
			return function.CallAsync<T>(functionParams);
		}

		/// <summary>
		/// Calls the specified function as a write operation
		/// </summary>
		/// <param name="contract">The contract instance on which to invoke the function</param>
		/// <param name="wallet">The wallet address of the contract owner</param>
		/// <param name="gas">The gas value</param>
		/// <param name="gasPrice">The gas price</param>
		/// <param name="value">The initial value of the contract</param>
		/// <param name="functionName">The name of the function to invoke</param>
		/// <param name="functionParams">The parameters to pass to the function</param>
		public static Task<string> CallWrite(this Contract contract, string functionName, string wallet, HexBigInteger gas, HexBigInteger gasPrice, HexBigInteger value, params object[] functionParams) {
			return contract.GetFunction(functionName).SendTransactionAsync(wallet, gas, gasPrice, value, functionParams);
		}

		/// <summary>
		/// Calls the specified function as a read operation
		/// </summary>
		/// <param name="function">The isntance of the function to invoke, which is the object returned by contractInstance.GetFunction("functionName")</param>
		/// <param name="wallet">The wallet address of the contract owner</param>
		/// <param name="gas">The gas value</param>
		/// <param name="gasPrice">The gas price</param>
		/// <param name="value">The initial value of the contract</param>
		/// <param name="functionParams">The parameters to pass to the function</param>
		public static Task<string> CallWrite(this Function function, string wallet, HexBigInteger gas, HexBigInteger gasPrice, HexBigInteger value, params object[] functionParams) {
			return function.SendTransactionAsync(wallet, gas, gasPrice, value, functionParams);
		}

		/// <summary>
		/// Calls the specified function as a write operation using default config
		/// </summary>
		/// <param name="contract">The contract instance on which to invoke the function</param>
		/// <param name="wallet">The wallet address of the contract owner</param>
		/// <param name="functionName">The name of the function to invoke</param>
		/// <param name="functionParams">The parameters to pass to the function</param>
		public static Task<string> CallWrite(this Contract contract, string functionName, string wallet, params object[] functionParams) {
			return CallWrite(contract, functionName, wallet, ConfigParams.DefaultGas, ConfigParams.DefaultGasPrice, ConfigParams.DefaultValue, functionParams);
		}

		/// <summary>
		/// Calls the specified function as a read operation using default config
		/// </summary>
		/// <param name="function">The isntance of the function to invoke, which is the object returned by contractInstance.GetFunction("functionName")</param>
		/// <param name="wallet">The wallet address of the contract owner</param>
		/// <param name="functionParams">The parameters to pass to the function</param>
		public static Task<string> CallWrite(this Function function, string wallet, params object[] functionParams) {
			return CallWrite(function, wallet, ConfigParams.DefaultGas, ConfigParams.DefaultGasPrice, ConfigParams.DefaultValue, functionParams);
		}

		/// <summary>
		/// Sends a signal to the associated node to start mining
		/// </summary>
		public static Task<bool> StartMining() {
			return Node.Miner.Start.SendRequestAsync(6);
		}

		/// <summary>
		/// Sends a signal to the associated node to stop mining
		/// </summary>
		public static Task<bool> StopMining() {
			return Node.Miner.Stop.SendRequestAsync();
		}
	}
}